accounts/urls.py
from django.shortcuts import redirect
from django.urls import path
from . import views
from django.contrib.auth.views import LoginView,LogoutView

app_name = "accounts"

urlpatterns = [
    path('signup/',views.signup,name = 'signup'),
    path('userlogin/',views.userlogin,name = 'userlogin'),
    path('logout/',LogoutView.as_view(),name = 'logout')
]

nnc/urls.py
from django.urls import path
from . import views

app_name = "nnc"

urlpatterns = [
    path('',views.home,name = 'home'),
    path('products/<slug:slug>/',views.productpage,name = 'product'),
    path('allproducts/',views.allproductpage, name = 'allproduct'),
    path('cart/',views.cart,name = 'cart'),
    path('addtocart/<int:pk>',views.addtocart,name = 'addtocart'),
    path('addtocartt/<int:pk>/<int:quantity>',views.addtocartt,name='addtocartt'),
    path('increase/<int:pk>',views.increaseqty,name = 'increase'),
    path('decrease/<int:pk>',views.decreaseqty,name = 'decrease'),
    path('remove/<int:pk>',views.remove,name = 'remove'),
    path('checkout/',views.checkout,name = 'checkout'),
    path('orders/',views.orders,name = 'orders'),
    path('order/<int:pk>',views.order_detail,name = 'orderdetail'),
    path('delivery/',views.delivery_page,name='delivery'),
    path('delivery/<int:pk>',views.delivery_detail,name='deliverydetail'),
    path('setdelivered/<int:pk>',views.set_delivered,name='setdelivered')
]

store/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('',include('nnc.urls')),
    path('contact/',views.contact,name = 'contact')
]
urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

nnc/models.py
from django.db import models
from django.db.models.fields import IntegerField
from django.template.defaultfilters import slugify


class Category(models.Model):
    title = models.CharField(max_length=50)
    category_image = models.ImageField(null = True, blank = True)
    heading = models.CharField(max_length=50)
    description = models.CharField(max_length=100)
    slug = models.SlugField(null = True)

    def save(self,*args, **kwargs):
        self.slug = slugify(self.title)
        super(Category,self).save(*args,**kwargs)

    def __str__(self):
        return self.title


class Product(models.Model):
    name = models.CharField(max_length = 50)
    weight = models.FloatField()
    brand = models.CharField(max_length=50)
    price = models.FloatField()
    product_image = models.ImageField()
    description = models.CharField(max_length=100)

    def __str__(self):
        return self.name

class CategoryProduct(models.Model):
    category = models.ForeignKey("nnc.Category",on_delete = models.CASCADE, null = True)
    product = models.ForeignKey("nnc.Product",on_delete=models.CASCADE, null = True)

    def __str__(self):
        return self.category.title + '-' + self.product.name

class Order(models.Model):
    user = models.ForeignKey("auth.User",on_delete = models.CASCADE)
    customer = models.ForeignKey("accounts.customer",on_delete = models.CASCADE)
    complete = models.BooleanField(default = False)
    total = models.IntegerField(default = 0)
    number_of_items = models.IntegerField(default = 0)
    date_ordered = models.DateTimeField(null = True)
    delivered = models.BooleanField(default = False)

    def __str__(self):
        return self.user.username + '-' + str(self.pk)

class OrderProduct(models.Model):
    order = models.ForeignKey("nnc.Order",on_delete = models.CASCADE)
    product = models.ForeignKey("nnc.CategoryProduct",on_delete = models.CASCADE)
    quantity = models.IntegerField(default = 1)

    def __str__(self):
        return str(self.order.pk) + '-' + self.product.product.name

    def calcprice(self):
        return self.quantity * self.product.product.price

nnc/views.py
from django.shortcuts import get_object_or_404, render, redirect
from django.template.defaultfilters import register
from django.views.generic import TemplateView
from django.utils import timezone
from .models import *
from accounts.models import customer


def home(request):
    context = {}

    context['categories'] = Category.objects.all

    return render(request,'home.html',context)

def productpage(request,slug):
    context = {}

    category = get_object_or_404(Category,slug = slug)
    cp = CategoryProduct.objects.filter(category = category)

    context['products'] = cp
    context['categories'] = Category.objects.all()

    return render(request, 'Products.html', context)

def allproductpage(request):
    context = {}

    context['categories'] = Category.objects.all()

    context['products'] = CategoryProduct.objects.all()


    return render(request,'allproducts.html',context)

def cart(request):
    context = {}

    user = request.user
    order = Order.objects.filter(user = user,complete = False)
    if order.exists():

        order = order[0]
        orderproduct = OrderProduct.objects.filter(order = order)
        total = 0

        for op in orderproduct:
            amount = op.calcprice()
            total = total + amount

        order.total = total
        order.save()

        context['total'] = total
        context['orderproduct'] = orderproduct
        context["count"] = OrderProduct.objects.filter(order = order).count()

    else:
        context["count"] = 0

    return render(request,'Cart.html',context)

def checkout(request):

    order = Order.objects.get(user = request.user,complete = False)
    order.number_of_items = OrderProduct.objects.filter(order = order).count()
    order.date_ordered = timezone.now()
    order.complete = True
    order.save()

    return render(request,'Recieved.html',{})

def orders(request):

    context = {}
    user = request.user

    order_list = Order.objects.filter(user = user,complete = True)
    context['orders'] = order_list

    return render(request,'previous.html',context)

def order_detail(request,pk):

    context = {}
    order = Order.objects.get(pk=pk)

    context['order'] = order

    orderproducts = OrderProduct.objects.filter(order = order)

    context['orderproducts'] = orderproducts
    
    return render(request, 'cartitemreview.html',context)

def delivery_page(request):

    context = {}
    order = Order.objects.filter(delivered = False)

    context['orders'] = order

    return render(request,'Deliveries.html',context)

def delivery_detail(request,pk):

    context = {}
    order = get_object_or_404(Order,pk=pk)
    orderproducts = OrderProduct.objects.filter(order = order)

    context['order'] = order
    context['orderproducts'] = orderproducts

    return render(request,'Deliveryitem.html', context)


# FUNCTIONALITIES
def addtocart(request,pk):

    product = get_object_or_404(CategoryProduct,pk=pk)
    order_list = Order.objects.filter(user = request.user, complete = False)
    
    if order_list.exists():
        order = order_list[0]
        orderproduct = OrderProduct.objects.filter(product = product, order = order)

        if orderproduct.exists():
            orderproduct = OrderProduct.objects.get(order = order,product = product)
            orderproduct.quantity = orderproduct.quantity + int(request.POST["quantity"])
            orderproduct.save()
            return redirect('nnc:product',slug = product.category.slug)
        
        else:
            orderproduct = OrderProduct.objects.create(order = order, product = product)
            orderproduct.quantity = request.POST["quantity"]
            orderproduct.save()
            return redirect('nnc:product',slug = product.category.slug)

    else:
        cust = customer.objects.get(user = request.user)
        order = Order.objects.create(user = request.user, customer = cust)
        orderproduct = OrderProduct.objects.create(order = order,product = product,quantity = request.POST["quantity"])
        return redirect('nnc:product',slug = product.category.slug)

def addtocartt(request,pk,quantity):

    product = get_object_or_404(CategoryProduct,pk=pk)
    order_list = Order.objects.filter(user = request.user, complete = False)
    
    if order_list.exists():
        order = order_list[0]
        orderproduct = OrderProduct.objects.filter(product = product, order = order)

        if orderproduct.exists():
            orderproduct = OrderProduct.objects.get(order = order,product = product)
            orderproduct.quantity = orderproduct.quantity + int(quantity)
            orderproduct.save()
            return redirect('nnc:product',slug = product.category.slug)
        
        else:
            orderproduct = OrderProduct.objects.create(order = order, product = product)
            orderproduct.quantity = quantity
            orderproduct.save()
            return redirect('nnc:product',slug = product.category.slug)

    else:
        cust = customer.objects.get(user = request.user)
        order = Order.objects.create(user = request.user, customer = cust)
        orderproduct = OrderProduct.objects.create(order = order,product = product,quantity = quantity)
        return redirect('nnc:cart')

def increaseqty(request,pk):

    orderproduct = get_object_or_404(OrderProduct,pk=pk)
    orderproduct.quantity += 1
    orderproduct.save()

    return redirect('nnc:cart')

def decreaseqty(request,pk):

    orderproduct = get_object_or_404(OrderProduct,pk=pk)
    if orderproduct.quantity == 1:
        return redirect('nnc:remove',pk=pk)
    else:
        orderproduct.quantity -= 1
        orderproduct.save()

    return redirect('nnc:cart')

def remove(request,pk):

    orderproduct = get_object_or_404(OrderProduct,pk=pk)
    orderproduct.delete()

    return redirect('nnc:cart')

def set_delivered(request,pk):

    order = get_object_or_404(Order,pk=pk)
    order.delivered = True
    order.save()
    
    return redirect('nnc:delivery')




        

nnc/templates/Cart.html
{% extends "base.html" %}
{% load static %}

{% block links %}
<link rel="stylesheet" href="{% static 'css/Cart.css' %}" media="screen">
<script src="{% static 'js/Cart.js' %}"></script>
{% endblock links %}


{% block content %}
<section class="u-align-left u-clearfix u-image u-shading u-section-1" src="" data-image-width="1280"
  data-image-height="825" id="sec-a068">
  <div class="u-clearfix u-sheet u-sheet-1">
    {% if count == 0 %}
    <h1 class="u-text u-text-default u-title u-text-1">No Items Yet!</h1>
    <p class="u-large-text u-text u-text-variant u-text-2">Order some nuts bro</p>
    {% else %}
    <h1 class="u-text u-text-default u-title u-text-1">Items on your Cart</h1>
    <p class="u-large-text u-text u-text-variant u-text-2">blamba boosa sooca</p>
    {% endif %}
  </div>
</section>
<section class="u-clearfix u-section-2 blamba" id="sec-3d60">
  <div class="u-clearfix u-sheet u-sheet-1">
    <div class="container">

      <section id="cart">
        {% for op in orderproduct %}
        <article class="product">
          <header>
            <a class="remove" href = "{% url 'nnc:remove' pk=op.pk %}">
              <img src="{{op.product.product.product_image.url}}" alt="">

              <h3>Remove product</h3>
            </a>
          </header>

          <div class="content">

            <h1>{{op.product.product.name}}</h1>

            {{op.product.product.description}}

            <!-- <div title="You have selected this product to be shipped in the color yellow." style="top: 0"
              class="color yellow"></div>
            <div style="top: 43px" class="type small">XXL</div> -->
          </div>

          <footer class="content">
            <a href = "{% url 'nnc:decrease' pk=op.pk %}"><span class="qt-minus">-</span></a>
            <span class="qt">{{op.quantity}}</span>
            <a href = "{% url 'nnc:increase' pk=op.pk %}"><span class="qt-plus">+</span></a>

            <h2 class="full-price">
              {{op.calcprice}}
            </h2>

            <h2 class="price">
              {{op.product.product.price}}
            </h2>
          </footer>
        </article>
        {% endfor %}
      </section>

    </div>

    <footer id="site-footer">
      <div class="container clearfix">

        <div class="left">
          <h2 class="subtotal">Subtotal: <span>{{total}}</span>₹</h2>
          <h3 class="tax">Number of Items: <span>{{count}}</span></h3>
          <!-- <h3 class="shipping">Customer: <span>5.00</span>₹</h3> -->
        </div>

        <div class="right">
          <h1 class="total">Total: <span>{{total}}</span>₹</h1>
          <a class="btn" href = "{% url 'nnc:checkout' %}">Checkout</a>
        </div>

      </div>
    </footer>
  </div>
</section>


{% endblock content %}

nnc/templates/Cartitemreview.html
{% extends "base.html" %}
{% load static %}

{% block links %}
<link rel="stylesheet" href="{% static 'css/cartitemreview.css' %}" media="screen">
<link rel="stylesheet" href="{% static 'css/nicepage.css' %}" media="screen">
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
  integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
  integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
{% endblock links %}

{% block content %}
    <section class="u-align-left u-clearfix u-image u-shading u-section-1" src="{% static 'images/choc.png' %}" data-image-width="1920" data-image-height="1080" id="sec-3bf7">
      <div class="u-clearfix u-sheet u-valign-middle u-sheet-1">
        <h1 class="u-text u-title u-text-1">Order no:&nbsp;{{order.pk}}</h1>
      </div>
    </section>
    <section class="u-black u-clearfix u-section-2" id="sec-9aa4">
      <div class="u-clearfix u-sheet u-sheet-1">
        <h1 class="u-custom-font u-text u-text-default u-text-1">Order Details :&nbsp;</h1>
        <h3 class="u-custom-font u-text u-text-default u-text-2">Date :&nbsp;{{order.date_ordered}}</h3>
        <h3 class="u-custom-font u-text u-text-default u-text-3">order total :&nbsp;{{order.total}}</h3>
        <h3 class="u-custom-font u-text u-text-default u-text-4">no. of items purchased :&nbsp;{{order.number_of_items}}</h3>
        <h3 class="u-custom-font u-text u-text-default u-text-5">items purchased :&nbsp;</h3>
        <div class="containerzz">
          <!-- start of first card da sundal -->
          {% for op in orderproducts %}
          <div class="card" style="width:400px;">
            <img class="card-img-top" src="{{op.product.product.product_image.url}}" alt="Card image">
            <div class="card-body">
              <h4 style="color: black;" class="card-title">{{op.product.product.name}}</h4>
              <p style="color: black;" class="card-text">Quantity : {{op.quantity}}</p>
              <p style="color: black;" class="card-text">Price : {{op.product.product.price}}</p>
              <a href="{% url 'nnc:addtocartt' pk=op.product.pk quantity=op.quantity %}" class="btn btn-primary">Order
                again</a>
            </div>
          </div>
          {% endfor %}
      </div>
    </section>
    <section class="u-black u-clearfix u-section-3" id="sec-7966">
      <div class="u-clearfix u-sheet u-sheet-1">
        <a href="{% url "nnc:orders" %}" class="u-btn u-btn-round u-button-style u-gradient u-none u-radius-27 u-text-body-alt-color u-btn-1"><span class="u-icon u-icon-1"><svg class="u-svg-content" viewBox="0 0 512 512" style="width: 1em; height: 1em;"><path d="m280 192a8 8 0 0 1 -8-8v-80a56 56 0 0 0 -112 0v80a8 8 0 0 1 -16 0v-80a72 72 0 0 1 144 0v80a8 8 0 0 1 -8 8z" fill="#dadcde"></path><path d="m296 472h-272l16-320h240z" fill="#eb423f"></path><path d="m360 472h-64l-16-320h64z" fill="#d13330"></path><path d="m328.47 431.99c-.16.01-.32.01-.48.01a8 8 0 0 1 -7.98-7.53l-16-272c-.01-.16-.01-.31-.01-.47h16.02l15.97 271.53a8.007 8.007 0 0 1 -7.52 8.46z" fill="#a82a27"></path><path d="m488 472h-64l-1-12.93v-.01l-15-195.06h64l14.75 191.69v.01z" fill="#eba72e"></path><path d="m456.8 431.96a7.322 7.322 0 0 1 -.81.04 8 8 0 0 1 -7.95-7.2l-.29-2.86-15.71-157.14a7.143 7.143 0 0 1 -.04-.8h16.04l15.72 157.21.2 1.99a8 8 0 0 1 -7.16 8.76z" fill="#e09f2c"></path><path d="m488 472h-9.62l-22.38-33.58-22.38 33.58h-9.62l-1-12.93v-.01l24.75-37.12 1.59-2.38a8.01 8.01 0 0 1 13.32 0l1.1 1.65 22.99 34.48v.01z" fill="#e09f2c"></path><path d="m424 472h-208l16-208h176z" fill="#f7b030"></path><path d="m328 416h-16a40.045 40.045 0 0 1 -40-40v-64a8 8 0 0 1 16 0v64a24.027 24.027 0 0 0 24 24h16a24.027 24.027 0 0 0 24-24v-64a8 8 0 0 1 16 0v64a40.045 40.045 0 0 1 -40 40z" fill="#e9eef2"></path><path d="m96 184h16v48h-16z" fill="#dadcde"></path><path d="m104 192a8 8 0 0 1 -8-8v-80a72 72 0 0 1 144 0v80a8 8 0 0 1 -16 0v-80a56 56 0 0 0 -112 0v80a8 8 0 0 1 -8 8z" fill="#e9eef2"></path><path d="m128 296h-48v-64l24-16 24 16z" fill="#f7b030"></path></svg><img></span>&nbsp;View your orders
        </a>
        <a href="{% url "nnc:home" %}" class="u-btn u-btn-round u-button-style u-gradient u-none u-radius-27 u-text-body-alt-color u-btn-2"><span class="u-icon u-icon-2"><svg class="u-svg-content" viewBox="0 0 512 512" style="width: 1em; height: 1em;"><g><g><path d="m76 257-30-15v-60h30z" fill="#665151"></path>
</g><g><path d="m226 332h-180v-90h180z" fill="#ff7f40"></path>
</g><path d="m136 242h90v90h-90z" fill="#f25a3c"></path><g id="_Snack_Booth_1_"><g><path d="m346 182h30v135h-30z" fill="#4d3535"></path>
</g><g><path d="m76 452h30v60h-30z" fill="#665151"></path>
</g><g><path d="m496 332h-105l15-30h90z" fill="#4d3535"></path>
</g>
</g><path d="m151 103.4v80.4l-60 30-75-37.5v-72.9l75.9-30z" fill="#ffb95a"></path><path d="m271 103.4v80.4l-60 30-60-30v-80.4l60-30z" fill="#f25a3c"></path><g><path d="m211 73.4v140.4l60-30v-80.4z" fill="#e63a3a"></path>
</g><path d="m406 103.4v72.9l-75 37.5-60-30v-80.4l67.5-30z" fill="#ff9833"></path><g><path d="m346 467h-330v-165h390v129.272l-20.229-7.515c-18.677-6.972-39.771 8.204-39.771 28.243z" fill="#ffb95a"></path>
</g><g><path d="m167.8 0 21.6 52.7-38.4 50.7h-135l50.7-103.4z" fill="#ffdc73"></path>
</g><path d="m271 103.4h-120l16.8-103.4h86.7l38.25 52.7z" fill="#ff7f40"></path><g><path d="m292.75 52.7-38.25-52.7h-43.5v103.4h60z" fill="#f25a3c"></path>
</g><path d="m406 103.4h-135l-16.5-103.4h100.8z" fill="#ffb95a"></path><path d="m211 467h135v-15c0-20.039 21.094-35.215 39.771-28.242l20.229 7.514v-129.272h-195z" fill="#ff9833"></path><circle cx="376" cy="452" fill="#4d3535" r="60"></circle><circle cx="376" cy="452" fill="#ffeacc" r="15"></circle>
</g></svg><img></span>&nbsp;Continue shopping
        </a>
      </div>
    </section>
    {% endblock content %}   
    
    

nnc/templates/Deliveries.html
{% extends "base.html" %}
{% load static %}

{% block links %}
<link rel="stylesheet" href="{% static 'css/deliveries.css' %}" media="screen">
{% endblock links %}

{% block content %}
<section class="u-align-left u-clearfix u-image u-shading u-section-1" src="" data-image-width="1280"
  data-image-height="845" id="sec-a068">
  <div class="u-clearfix u-sheet u-sheet-1">
    <h1 class="u-text u-text-default u-title u-text-1">Delivery Status&nbsp;</h1>
  </div>
</section>
<section class="u-black u-clearfix u-section-2" id="sec-3d60">
  <div class="u-clearfix u-sheet u-sheet-1">
    <h2 class="u-text u-text-default u-text-1">Pending Orders :&nbsp;</h2>
    <div class="cards">
      {% for order in orders %}
        
      
      <div class="card card-1">
        <div class="card__icon"></div>
        <p class="card__exit"></p>
        <h2 class="card__title">Order Number : {{order.pk}}<br><br> Order date : {{order.date_ordered}}</h2>
        <p class="card__apply">
          <a class="card__link" style="color: red;" href="{% url 'nnc:deliverydetail' pk=order.pk %}">View Order </a>
        </p>
      </div>

      {% endfor %}
    </div>
  </div>
</section>
{% endblock content %}

nnc/templates/Products.html
{% extends "base.html" %}
{% load static %}
{% block links %}
<link rel="stylesheet" href="{% static 'css/nicepage.css' %}" media="screen">
<link rel="stylesheet" href="{% static 'css/product.css' %}">
<link rel="stylesheet" href="{% static 'css/Products.css' %}" media="screen">
<link id="u-theme-google-font" rel="stylesheet"
  href="https://fonts.googleapis.com/css?family=Roboto:100,100i,300,300i,400,400i,500,500i,700,700i,900,900i|Open+Sans:300,300i,400,400i,600,600i,700,700i,800,800i">
<link id="u-page-google-font" rel="stylesheet" href="https://fonts.googleapis.com/css?family=Julius+Sans+One:400">
{% endblock links %}

{% block content %}

      

<section class="u-align-left u-clearfix u-image u-shading u-section-1" src="" data-image-width="1920"
  data-image-height="1080" id="sec-3bf7">
  <div class="u-clearfix u-sheet u-sheet-1">
    <h1 class="u-text u-text-default u-title u-text-1">Our products</h1>
  </div>
</section>



<section class="u-black u-clearfix u-section-2" id="sec-9aa4">
  
  <div class="u-clearfix u-sheet u-sheet-1">

    <!-- START OF FIRST CARD DA SID -->
    

    {% for categoryproduct in products %}

    <div id="container" class="containerss">


      <div class="product-details">

        <h1>{{categoryproduct.product.name}}</h1>

        <h4 class="information">Weight :&nbsp {{categoryproduct.product.weight}} gms</h4>

        <h4 class="information">Price : &nbsp<i class="fa fa-rupee-sign"></i>{{categoryproduct.product.price}}</h4>

        {% if user.is_authenticated %}
        <form action="{% url 'nnc:addtocart' pk=categoryproduct.pk %}" method="post">
          {% csrf_token %}
          <h4 class="information">Quantity : &nbsp
            <div class="dropdown">
              <select name="quantity" class="dropdown-select">
                <option value="1">Select</option>
                <option value="1">1</option>
                <option value="2">2</option>
                <option value="3">3</option>
                <option value="4">4</option>
                <option value="5">5</option>
              </select>
            </div>
          </h4>

          <div class="control">

            <button class="btn alert">
              <!-- <span class="price">300</span> -->
              <span class="shopping-cart"><i class="fa fa-shopping-cart" aria-hidden="true"></i></span>
              <span class="buy">Add Item to Cart</span>
            </button>

          </div>
        </form>
        {% else %}
        <form action="{% url 'accounts:userlogin' %}" method="GET">
          {% csrf_token %}
          <h4 class="information">Quantity : &nbsp
            <div class="dropdown">
              <select name="quantity" class="dropdown-select">
                <option value="1">Select</option>
                <option value="1">1</option>
                <option value="2">2</option>
                <option value="3">3</option>
                <option value="4">4</option>
                <option value="5">5</option>
              </select>
            </div>
          </h4>
          <div class="control">
            <button class="btn alert">
              <!-- <span class="price">300</span> -->
              <span class="shopping-cart"><i class="fa fa-shopping-cart" aria-hidden="true"></i></span>
              <span class="buy">Add Item to Cart</span>
            </button>

          </div>
        </form>
        {% endif %}
      </div>

      <div class="product-image">

        <img src="{{categoryproduct.product.product_image.url}}" alt="">


        <div class="info">
          <h2 class="desc"> Description</h2>
          <ul>
            <li><strong>Desc : </strong>{{categoryproduct.product.description}}</li>
            <li><strong>Brand : </strong>{{categoryproduct.product.brand}}</li>

          </ul>
        </div>
      </div>

    </div>

    <!-- END OF A CARD -->
    {% endfor %}
    <!-- </section>
<section class="u-black u-clearfix u-section-3" id="sec-9202">
  <div class="u-align-left u-clearfix u-sheet u-sheet-1">
    <a href="Cart.html" data-page-id="685206799" class="u-btn u-button-style u-none u-text-hover-palette-2-base u-text-palette-1-base u-btn-1"><span class="u-icon u-text-palette-2-base"><svg class="u-svg-content" viewBox="0 0 511.334 511.334" style="width: 1em; height: 1em;"><path d="m506.887 114.74c-3.979-5.097-10.086-8.076-16.553-8.076h-399.808l-5.943-66.207c-.972-10.827-10.046-19.123-20.916-19.123h-42.667c-11.598 0-21 9.402-21 21s9.402 21 21 21h23.468l23.018 256.439c.005.302-.01.599.007.903.047.806.152 1.594.286 2.37l.842 9.376c.016.177.034.354.055.529 2.552 22.11 13.851 41.267 30.19 54.21-8.466 10.812-13.532 24.407-13.532 39.172 0 35.106 28.561 63.667 63.666 63.667 35.106 0 63.667-28.561 63.667-63.667 0-7.605-1.345-14.9-3.801-21.667h114.936c-2.457 6.767-3.801 14.062-3.801 21.667 0 35.106 28.561 63.667 63.667 63.667s63.667-28.561 63.667-63.667-28.561-63.667-63.667-63.667h-234.526c-15.952 0-29.853-9.624-35.853-23.646l335.608-19.724c9.162-.538 16.914-6.966 19.141-15.87l42.67-170.67c1.567-6.272.158-12.918-3.821-18.016z"></path></svg><img></span>&nbsp;View cart
    </a>
  </div>
</section> -->

    <section class="u-black u-clearfix u-section-2" id="sec-f66f">
      <div class="u-clearfix u-sheet u-sheet-1">
        <h1 class="cats" style="font-size: 5rem;">You may also be interested in...</h1>
        <div class="container categ">
          {% for category in categories %}
          <a href="{% url 'nnc:product' slug=category.slug %}">
            <div id="navchoc" class="card">
              <div class="face face1">
                <div class="content">
                  <div class="icon">
                    <h1 class="cardreader" style="font-size: 2rem;margin-top: 2%;">{{category.title}}</h1>
                    <img class="cookief" src="{{category.category_image.url}}" alt="">
                  </div>
                </div>
              </div>
              <div class="face face2">
                <div class="content">
                  <h3>
                    <p>{{category.heading}}</p>
                  </h3>
                  <p>{{category.description}}</p>
                </div>
              </div>
            </div>
          </a>

          {% endfor %}

        </div>
        
    </section>
    <style class="u-overlap-style">
      .u-overlap:not(.u-sticky-scroll) .u-header {}
    </style>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
    <script src="js/scripts.js"></script>
    <script src="{% static 'js/products.js' %}"></script>
    {% endblock content %}